# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: cimg/rust:1.49
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Install stable toolchain
          command: rustup toolchain install stable
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo test
            rustup run stable cargo test -p crypto
            rustup run stable cargo test -p hooks
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: cimg/rust:1.49
    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Install stable toolchain
          command: rustup toolchain install stable
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build --release
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
          # taken to be the root directory of the workspace.
          root: /home/circleci/project
          # Must be relative path from root
          paths:
            - target/release
  publish-github-release:
    docker:
      - image: cimg/go:1.15
    working_directory: /home/circleci/project
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: make file executable 
          command: |
            ls -al /home/circleci/project/target/release
            chmod +x /home/circleci/project/target/release/wg-conf
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            export VERSION=$(/home/circleci/project/target/release/wg-conf --version | sed 's/ /_/g')
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} -delete \
                ${VERSION} /home/circleci/project/target/release/wg-conf
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build-and-release:
    # Run the welcome/run job in its own container
    jobs:
      - test
      - build
          requires:
            - test
      - publish-github-release:
          requires:
            - build
          filters:
            branches: 
              only: master